language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
# env:
  # global:
  # - secure: 414uFgwd2yK2GlUSX0+L9GAuLOUrd1m8WyNd0z1jmYNMYTQMWR7FqWwtKfRYhPPpFYqJqxHNUDUbJYQH3lRPY3jAJ7e42PP9lIvQd8IlALkF81mNNtmyOSEgP84a2U0OTD1XAh7J6IYpDvyC8bWVb8oV61WMkU6KvLQ90V5y7Om1K7HDpnIeb3jvoBdTdyPwYVkuSyYwkJpN4fyPzsohwCqWfnfSiiGhX+WpDe1WK7KNbYiYSYSetxSYXM0Z6FDVqI+pzSphhkV0C84KkTFAyZEpZU6JmSppm+QgBGslIxijDNgxQg8ZCs1pJKLNCj++grqoQU1pBLTgDzCcnnJMVLjIDZ0ecSG3SJatH64fZFbWHFcmbLTgsvoinWvPh2XmESfQDfnvl8VaKUS80K/zDL0x6ts2OKNSG2JTLBtqtj6KiNUhu/sFRLDGYr/VoR6aYCJ8adfWWBi9VnyfUxbHszGGsiTs1TJFO0zOEmvndLTfzlB2Evj1tV3MGBGvXPFOWiKSPcET+k6ABFOlKbkkySSK6UQYakvIckwypeZBz24J1GdEe5LSngfk4fTrpSe7ct39sGKw4vDzdDjTSk5mCMwghaCAYKum9D2WaAuWjFaQVScIUqYtVp27dR9pIr7W95z/AQwJz6Hk6yrjYVBK/kZnbANFs6oksrmBZ8lBJHc=
deploy:
  provider: heroku
  api_key:
    secure: "MO8h2HTtfupXrsd1rA3Qjky3+TsaGURnKl1az9GQPJWTwj/Z/7Sh3/9n6m/bWSHcEtvYz9o/kFFxva7R8chWzltj3VtDDmJmP9xLRXfcWM60T6wbaEg8aWmbLB7Rt5vZw8n1g32X7lMjllqWgNQxCmBjO2/vzdWJVtvcTIbr3+PPjpHSp2UR7LwJwjuzygBy6GhBxyPUoNBhOkOWQlQSjH8Gfb5vbRYSgn8xTQXvjXIornf52JvlIv+rw19mo4EBsQuXhl67mYrFeUPTBMvLgBLaNRXmb+RDaZkxhvj6Cb4suFnh5yMFVg3NUd4wyY3ARbvGH+9NgbULEmKxIFxO7n8BdUc5ZLONAfspuywTJjwQJe9HFS659ZF4Tt//M1mzprmzGs0soPYNNMYTpWFLix8CeQE6z/vwdiGq7Aq29lzA9qQ2+FUTp/H+o2bzWbFmOEa+/axUqOwy7/rrnJJhv2vfQkpQq3wE90dYQAFIUWuoi50Q+UHtRJePrq5qkJeh/IozuzZpC177fsjya6jKinib85ASjHOyCwa2j9lU6zEtaeIw3mNtJ+3L5lqrL3hvTWpWZGRTroeCglTM2ull/0wAyKyJY5xu2VJB9xMlSIgTqBEzCMci+u7jORRFWmWGPhG7tZKgTx2BoCabA00FT3HEiIkRxcsX8rlndPOxrOs="
  app: pet-adoption-denver
  skip_cleanup: true
  on:
    branch: main
  run: rails db:migrate
